### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by zh8008** [gatech-genemark/Mgcod#3] opened 2023-09-07 08:17 UTC
Hi, Aaron

Your project has greatly addressed my issues, and I sincerely appreciate it. 

However, can your software run in multithreaded mode to improve its operational efficiency? Because my Fasta file size was 37MB, it has been running for almost a week without producing any output results, and the background status consistently shows that it's running in single-threaded mode. I'm not sure where the problem occurred. My code as followed:

`nohup mgcod.py -i /disks/RAID6_120TB/hz/m_mnpk_npk_ck/Mgcod2/all_votu2_5000_1.fasta -r --isoforms -v -m ./all_votu2_plots -p all_votu2_mgm_results -o all_votu2_results &`

Any suggestion on how to solve this? Thanks！

Best,
He

**Comment by arpfennig** [comment] 2023-09-07 14:16
Hi He,

That is odd, it shouldn't take that long. Do you mind sharing your input file so that I can look into it? Also what version are you using?

Anyway, mgcod itself is not parallelized itself. However, we provide a script `multiprocess_mgcod.py` that runs mgcod on multiple genomes/contigs in parallel. Just split the genomes/contigs in your input fasta file into individual files and provide a text file containing the paths to the individual genomes/contigs (one per line) using the `--genomes` flag. All other input options remain the same. 

Best,
Aaron

**Comment by zh8008** [comment] 2023-09-07 14:50
Dear, Aaron

Thank you for your response！

I selected sequences longer than 5000 base for the Fasta file. The file content was as followed: 
<img width="1439" alt="image" src="https://github.com/gatech-genemark/Mgcod/assets/45389512/41978ec5-89eb-4446-928f-ccdcfd90a3ec">

Best,
He

**Comment by zh8008** [comment] 2023-09-07 18:25
Dear, Aaron

I followed your suggestion and used the multiprocess_mgcod.py script. At the same time, I divided the previous Fasta file into multiple Fasta formatted genome files based on the genome ID, and wrote the paths of these genome files in the genomes.txt file. Unfortunately, an error occurred during the operation:

<img width="1433" alt="image" src="https://github.com/gatech-genemark/Mgcod/assets/45389512/51f62aed-4504-4b7c-baf9-dc511ae89cb3">

my codes as followed:

`multiprocess_mgcod.py --genomes genomes.txt -r --isoforms -m ./plots -p mgm_results/ --threads 180 -o results/`

The file genomes.txt content was as followed:

<img width="1073" alt="image" src="https://github.com/gatech-genemark/Mgcod/assets/45389512/aafcedda-f0b3-46cf-822a-012bb1602fd3">

I also used the `conda update mgcod` code to update Mgcod. But it still hasn't resolved the error report. The Mgcod version was 1.0.1.

Any suggestion on how to solve this? Thanks！

Best,
He

**Comment by zh8008** [comment] 2023-09-07 18:38
**Dear, Aaron**

I followed your suggestion and used the `multiprocess_mgcod.py` script. At the same time, I divided the previous Fasta file into multiple Fasta formatted genome files based on the genome ID, and wrote the paths of these genome files in the `genomes.txt` file. Unfortunately, **an error occurred during the operation:**

<img width="1435" alt="image" src="https://github.com/gatech-genemark/Mgcod/assets/45389512/d5c4b244-74bb-4f08-b271-3295c4259aa7">

My codes as followed:

`multiprocess_mgcod.py --genomes genomes.txt -r --isoforms -m ./plots -p mgm_results/ --threads 180 -o results/
`

The file `genomes.txt` content was as followed:

<img width="1075" alt="image" src="https://github.com/gatech-genemark/Mgcod/assets/45389512/a1588e5a-38a3-4197-9819-24a85e03c9ad">

I also used the `conda update mgcod` code to update **Mgcod**. But it still hasn't resolved the error report. The **Mgcod** version was **1.0.1.**

Any suggestion on how to solve this? Thanks！

**Best,
He**

**Comment by arpfennig** [comment] 2023-09-07 18:41
Hi He,

I fixed the Namespace error. It will take me some time to update the conda package, but you can pull it from GitHub in the meantime.

However, this is a different problem. Do you mind sharing your original input fasta file? I would like to try to reproduce your runtime issue.

Thanks,
Aaron

**Comment by zh8008** [comment] 2023-09-07 19:23
Dear, Aaron

Due to the size limit of the uploaded file (25MB), I can only upload some of the file content (these sequences are extracted from the original 3000 sequences with 2000 sequences). But I think it can already represent the problem I encountered, as the runtime of running this file is also very long, I haven't received any results yet

This is the link:[https://github.com/zh8008/2]

If you find the problem, please let me know,Thanks！

Best,
He

**Comment by zh8008** [comment] 2023-09-07 19:34
Dear, Aaron

I am planning to download and install Mgcod again from Github instead of using Conda installation. Would this plan solve the issue?

Best,
He

**Comment by arpfennig** [comment] 2023-09-08 16:00
Hi He,

Thanks for providing the file. 

I just analyzed the ~2000 sequences in ~11 minutes using 16 threads on an Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz. I split the multifasta file using this command: `seqkit split -i 2.fasta`. Then I analyzed the individuals contigs using `multiprocess_mgcod.py --genomes genomes.txt -p mgm/ -o results/ -r --isoforms --threads 16 --batch_size 32`.

The runtime of Mgcod could definitely improved by implementing some steps in smarter ways but I haven't gotten to it. 
I'm not sure why you don't get any results. However, what I noted is that you try to use 180 threads. In this case, you may want to reduce the batch size using the `--batch_size` argument. `multiprocess_mgcod.py` splits the genomes into batches of 256 by default. Thus, you won't leverage all your cores if you only have ~3000 contigs. 

If you still have problems, you could also try to run it on a single sequence and check the log file for where it gets stuck.

A side note on your data: I highly recommend running Mgcod on individual contigs. First, this allows using `multiprocess_mgcod.py`, speeding up your analyses. Second, I observed a mix of different genetics codes in the sequences you provided (i.e., in some contigs Mgcod predicted standard code and TGA reassignment and in others standard code and TAG reassignment). 

Furthermore, if you analyze them all together, Mgcod would catch only TGA or TAG reassignment depending on which one is more frequent as we only allow it to predict two different genetic codes. This is because no bacteria/phage has been found with 3 and it allows us to reduce false positives.

I hope this helps,
Aaron

**Comment by zh8008** [comment] 2023-09-09 06:09
Dear, Aaron

I completed the calculation through the `multiprocess_mgcod.py` you resubmitted. 

Thanks for your help!

Best,
He

**Closed as completed** 2023-09-09 06:10 UTC
